[package]
name = "jcc"
version = "0.1.0"
authors = ["Andrew Young <andrewy@indeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
encoding = "0.2"
regex = "1"
